name: Run Tests

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Enable Corepack
        run: corepack enable
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "yarn"
      - name: Install dependencies
        run: yarn install --immutable
      - name: Run tests
        run: yarn test-no-integration
